### ISSUE TITLE
[1.16.3][Issue] Spiders won't attack from ceiling

### ISSUE THREAD

**Issue by Warrof** [TheCyberBrick/Spiders-2.0#13]
Just started playing with this mod today... It's amazing, anyways while caving a spider came at me that was on the ceiling, got right above me and just sat there... No attack or anything.

**Comment by TheCyberBrick** [comment]
The pathfinding range is limited (as it is for all mobs), but due to the increased complexity of having to fully pathfind in 3D the paths sometimes end being shorter. Could be that the ceiling was too high and it couldn't find a full path towards the player.

**Comment by Warrof** [comment]
I suppose, but every time that I've seen this happen I was in a cave tunnel.  Will keep checking this out.

**Comment by TheCyberBrick** [comment]
This has now been improved with an increased path finder range.
