### ISSUE TITLE
[1.16.1] [Issue] Spam message about spiders in the console

### ISSUE THREAD

**Issue by Meskino** [TheCyberBrick/Spiders-2.0#14]
1 | 05.10 19:10:49 [PebbleHost] Received start command
-- | --
2 | 05.10 19:10:49 [PebbleHost] Starting server!
3 | 05.10 19:10:50 [PebbleHost Loader] -----------------------------------
4 | 05.10 19:10:50 [PebbleHost Loader] PebbleHost Server Loader Starting...
5 | 05.10 19:10:50 [PebbleHost Loader] The following settings have been detected: RAM: -Xmx5120M, JAR: forge.jar, SERVERID: 138135, SIZE: 107M
6 | 05.10 19:10:50 [PebbleHost Loader] Testing server configuration...
7 | 05.10 19:10:50 [PebbleHost Loader] Server loader version: v3.0.4 (using configuration version v1.3.6)
8 | 05.10 19:10:51 [PebbleHost Loader] Jar passed checksum check
9 | 05.10 19:10:51 [PebbleHost Loader] Server passed size check
10 | 05.10 19:10:51 [PebbleHost Loader] Server passed file check
11 | 05.10 19:10:51 [PebbleHost Loader] Configuring your servers settings...
12 | 05.10 19:10:51 [PebbleHost Loader] Server passed all checks, Booting...
13 | 05.10 19:10:51 [PebbleHost Loader] -----------------------------------
14 | 05.10 19:10:52 [Server] Startup 2020-10-05 23:10:52,803 main WARN Advanced terminal features are not available in this environment
15 | 05.10 19:10:52 [Server] main/INFO [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--gameDir, ., --launchTarget, fmlserver, --fml.forgeVersion, 32.0.108, --fml.mcpVersion, 20200625.160719, --fml.mcVersion, 1.16.1, --fml.forgeGroup, net.minecraftforge, nogui]
16 | 05.10 19:10:52 [Server] main/INFO [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 6.1.1+74+master.966c698 starting: java version 1.8.0_242 by Oracle Corporation
17 | 05.10 19:10:53 [Server] main/INFO [ne.mi.fm.lo.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
18 | 05.10 19:10:53 [Server] main/INFO [mixin/]: SpongePowered MIXIN Subsystem Version=0.8 Source=file:/libraries/org/spongepowered/mixin/0.8/mixin-0.8.jar Service=ModLauncher Env=SERVER
19 | 05.10 19:10:54 [Server] main/INFO [cp.mo.mo.LaunchServiceHandler/MODLAUNCHER]: Launching target 'fmlserver' with arguments [--gameDir, ., nogui]
20 | 05.10 19:11:06 [Server] modloading-worker-9/INFO [ne.mi.co.ForgeMod/FORGEMOD]: Forge mod loading, version 32.0.108, for MC 1.16.1 with MCP 20200625.160719
21 | 05.10 19:11:06 [Server] modloading-worker-9/INFO [ne.mi.co.MinecraftForge/FORGE]: MinecraftForge v32.0.108 Initialized
22 | 05.10 19:11:07 [Server] main/ERROR [minecraft/Util]: No data fixer registered for spiderstpo:better_spider
23 | 05.10 19:11:08 [Server] main/ERROR [minecraft/Util]: No data fixer registered for spiderstpo:better_cave_spider
24 | 05.10 19:11:08 [Server] Forge Version Check/INFO [ne.mi.fm.VersionChecker/]: [forge] Starting version check at https://files.minecraftforge.net/maven/net/minecraftforge/forge/promotions_slim.json
25 | 05.10 19:11:08 [Server] Forge Version Check/INFO [ne.mi.fm.VersionChecker/]: [forge] Found status: BETA Current: 32.0.108 Target: 32.0.108
26 | 05.10 19:11:10 [Server] main/INFO [mojang/YggdrasilAuthenticationService]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', name='PROD'
27 | 05.10 19:11:11 [Server] main/WARN [minecraft/Commands]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
28 | 05.10 19:11:11 [Server] main/WARN [minecraft/Commands]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
29 | 05.10 19:11:11 [Server] main/WARN [minecraft/Commands]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
30 | 05.10 19:11:11 [Server] main/WARN [minecraft/Commands]: Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
31 | 05.10 19:11:11 [Server] main/WARN [minecraft/Commands]: Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
32 | 05.10 19:11:11 [Server] main/INFO [minecraft/SimpleReloadableResourceManager]: Reloading ResourceManager: Default, forge-1.16.1-32.0.108-universal.jar, spiders-2.0-1.16.1-1.0.1.jar
33 | 05.10 19:11:12 [Server] Worker-Main-11/INFO [minecraft/RecipeManager]: Loaded 7 recipes
34 | 05.10 19:11:13 [Server] Worker-Main-11/INFO [minecraft/AdvancementList]: Loaded 927 advancements
35 | 05.10 19:11:14 [Server] Server thread/INFO [minecraft/DedicatedServer]: Starting minecraft server version 1.16.1
36 | 05.10 19:11:14 [Server] Server thread/INFO [minecraft/DedicatedServer]: Loading properties
37 | 05.10 19:11:14 [Server] Server thread/INFO [minecraft/DedicatedServer]: Default game type: SURVIVAL
38 | 05.10 19:11:14 [Server] Server thread/INFO [minecraft/DedicatedServer]: Generating keypair
39 | 05.10 19:11:14 [Server] Server thread/INFO [minecraft/DedicatedServer]: Starting Minecraft server on **.**.**.**:25572
40 | 05.10 19:11:14 [Server] Server thread/INFO [minecraft/NetworkSystem]: Using epoll channel type
41 | 05.10 19:11:14 [Server] Server thread/WARN [ne.mi.co.ForgeConfigSpec/CORE]: Configuration file ./world/serverconfig/forge-server.toml is not correct. Correcting
42 | 05.10 19:11:14 [Server] Server thread/WARN [ne.mi.co.ForgeConfigSpec/CORE]: Incorrect key server was corrected from null to SimpleCommentedConfig:{}
43 | 05.10 19:11:14 [Server] Server thread/WARN [ne.mi.co.ForgeConfigSpec/CORE]: Incorrect key server.removeErroringEntities was corrected from null to false
44 | 05.10 19:11:14 [Server] Server thread/WARN [ne.mi.co.ForgeConfigSpec/CORE]: Incorrect key server.removeErroringTileEntities was corrected from null to false
45 | 05.10 19:11:14 [Server] Server thread/WARN [ne.mi.co.ForgeConfigSpec/CORE]: Incorrect key server.fullBoundingBoxLadders was corrected from null to false
46 | 05.10 19:11:14 [Server] Server thread/WARN [ne.mi.co.ForgeConfigSpec/CORE]: Incorrect key server.zombieBaseSummonChance was corrected from null to 0.1
47 | 05.10 19:11:14 [Server] Server thread/WARN [ne.mi.co.ForgeConfigSpec/CORE]: Incorrect key server.zombieBabyChance was corrected from null to 0.05
48 | 05.10 19:11:14 [Server] Server thread/WARN [ne.mi.co.ForgeConfigSpec/CORE]: Incorrect key server.logCascadingWorldGeneration was corrected from null to true
49 | 05.10 19:11:14 [Server] Server thread/WARN [ne.mi.co.ForgeConfigSpec/CORE]: Incorrect key server.fixVanillaCascading was corrected from null to false
50 | 05.10 19:11:14 [Server] Server thread/WARN [ne.mi.co.ForgeConfigSpec/CORE]: Incorrect key server.dimensionUnloadQueueDelay was corrected from null to 0
51 | 05.10 19:11:14 [Server] Server thread/WARN [ne.mi.co.ForgeConfigSpec/CORE]: Incorrect key server.clumpingThreshold was corrected from null to 64
52 | 05.10 19:11:14 [Server] Server thread/WARN [ne.mi.co.ForgeConfigSpec/CORE]: Incorrect key server.treatEmptyTagsAsAir was corrected from null to false
53 | 05.10 19:11:14 [Server] Server thread/WARN [ne.mi.co.ForgeConfigSpec/CORE]: Incorrect key server.fixAdvancementLoading was corrected from null to true
54 | 05.10 19:11:14 [Server] Server thread/INFO [minecraft/DedicatedServer]: Preparing level "world"
55 | 05.10 19:11:15 [Server] Server thread/WARN [minecraft/MinecraftServer]: Unable to find spawn biome
56 | 05.10 19:11:21 [Server] Server thread/INFO [minecraft/MinecraftServer]: Preparing start region for dimension minecraft:overworld
57 | 05.10 19:11:21 [Server] Worker-Main-8/INFO [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 0%
58 | 05.10 19:11:22 [Server] Worker-Main-8/INFO [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 0%
59 | 05.10 19:11:22 [Server] Worker-Main-8/INFO [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 3%
60 | 05.10 19:11:23 [Server] Worker-Main-11/INFO [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 8%
61 | 05.10 19:11:23 [Server] Worker-Main-13/INFO [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 13%
62 | 05.10 19:11:24 [Server] Worker-Main-14/INFO [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 17%
63 | 05.10 19:11:24 [Server] Worker-Main-8/INFO [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 22%
64 | 05.10 19:11:25 [Server] Worker-Main-12/INFO [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 26%
65 | 05.10 19:11:25 [Server] Worker-Main-14/INFO [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 34%
66 | 05.10 19:11:26 [Server] Worker-Main-11/INFO [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 34%
67 | 05.10 19:11:26 [Server] Worker-Main-8/INFO [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 43%
68 | 05.10 19:11:27 [Server] Worker-Main-14/INFO [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 43%
69 | 05.10 19:11:27 [Server] Worker-Main-9/INFO [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 55%
70 | 05.10 19:11:28 [Server] Worker-Main-10/INFO [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 60%
71 | 05.10 19:11:29 [Server] Worker-Main-8/INFO [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 68%
72 | 05.10 19:11:29 [Server] Worker-Main-12/INFO [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 68%
73 | 05.10 19:11:30 [Server] Worker-Main-10/INFO [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 79%
74 | 05.10 19:11:30 [Server] Worker-Main-10/INFO [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 79%
75 | 05.10 19:11:31 [Server] Worker-Main-8/INFO [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 91%
76 | 05.10 19:11:31 [Server] Worker-Main-8/INFO [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 91%
77 | 05.10 19:11:31 [Server] Server thread/INFO [minecraft/LoggingChunkStatusListener]: Time elapsed: 9726 ms
78 | 05.10 19:11:31 [Server] Startup [minecraft/DedicatedServer]: Done (16.650s)! For help, type "help"
79 | 05.10 19:13:16 [Server] User Authenticator #1/INFO [minecraft/ServerLoginNetHandler]: UUID of player RayWoss is ed35e2a8-593d-494c-a3d0-b7cd240b169c
80 | 05.10 19:13:18 [Server] Server thread/INFO [ne.mi.co.AdvancementLoadFix/]: Using new advancement loading for net.minecraft.advancements.PlayerAdvancements@13ddbbd1
81 | 05.10 19:13:18 [Connect] User RayWoss, IP **.**.**.**
82 | 05.10 19:13:18 [PebbleHost] RayWoss ran command Message of the Day
83 | 05.10 19:13:18 [Server] Server thread/INFO [minecraft/DedicatedServer]: RayWoss joined the game
84 | 05.10 19:13:18 [Server] Netty Epoll Server IO #4/ERROR [minecraft/ArgumentTypes]: Could not serialize net.minecraftforge.server.command.ModIdArgument@6740bc97 (class net.minecraftforge.server.command.ModIdArgument) - will not be sent to client!
85 | 05.10 19:13:18 [Server] Netty Epoll Server IO #4/ERROR [minecraft/ArgumentTypes]: Could not serialize net.minecraftforge.server.command.EnumArgument@65626e0 (class net.minecraftforge.server.command.EnumArgument) - will not be sent to client!
86 | 05.10 19:13:19 [Server] Server thread/WARN [minecraft/ServerWorld]: Tried to add entity minecraft:spider but it was marked as removed already
87 | 05.10 19:13:19 [Server] Server thread/WARN [minecraft/ServerWorld]: Tried to add entity minecraft:spider but it was marked as removed already
88 | 05.10 19:13:19 [Server] Server thread/WARN [minecraft/ServerWorld]: Tried to add entity minecraft:spider but it was marked as removed already
89 | 05.10 19:13:20 [Server] Server thread/WARN [minecraft/ServerWorld]: Tried to add entity minecraft:spider but it was marked as removed already
90 | 05.10 19:13:21 [Server] Server thread/WARN [minecraft/ServerWorld]: Tried to add entity minecraft:spider but it was marked as removed already
91 | 05.10 19:13:22 [Server] Server thread/WARN [minecraft/ServerWorld]: Tried to add entity minecraft:spider but it was marked as removed already
92 | 05.10 19:13:23 [Server] Server thread/WARN [minecraft/MinecraftServer]: Can't keep up! Is the server overloaded? Running 2023ms or 40 ticks behind
93 | 05.10 19:14:21 [Server] Server thread/WARN [minecraft/ServerWorld]: Tried to add entity minecraft:spider but it was marked as removed already
94 | 05.10 19:14:36 [Server] Server thread/WARN [minecraft/ServerWorld]: Tried to add entity minecraft:spider but it was marked as removed already
95 | 05.10 19:15:02 [Server] Server thread/WARN [minecraft/ServerWorld]: Tried to add entity minecraft:spider but it was marked as removed already
96 | 05.10 19:15:11 [Server] Server thread/WARN [minecraft/ServerWorld]: Tried to add entity minecraft:spider but it was marked as removed already
97 | 05.10 19:15:25 [Server] Server thread/WARN [minecraft/ServerWorld]: Tried to add entity minecraft:spider but it was marked as removed already
98 | 05.10 19:16:02 [Server] Server thread/WARN [minecraft/ServerWorld]: Tried to add entity minecraft:spider but it was marked as removed already
99 | 05.10 19:16:10 [Server] Server thread/WARN [minecraft/ServerWorld]: Tried to add entity minecraft:spider but it was marked as removed already
100 | 05.10 19:16:45 [Server] Server thread/WARN [minecraft/ServerWorld]: Tried to add entity minecraft:spider but it was marked as removed already
101 | 05.10 19:16:56 [Server] Server thread/WARN [minecraft/ServerWorld]: Tried to add entity minecraft:spider but it was marked as removed already
102 | 05.10 19:17:15 [Server] Server thread/INFO [minecraft/DedicatedServer]: [RayWoss: Set own game mode to Creative Mode]
103 | 05.10 19:17:19 [Server] Server thread/WARN [minecraft/ServerWorld]: Tried to add entity minecraft:spider but it was marked as removed already
104 | 05.10 19:17:47 [Server] Server thread/WARN [minecraft/ServerWorld]: Tried to add entity minecraft:spider but it was marked as removed already
105 | 05.10 19:18:00 [Server] Server thread/WARN [minecraft/ServerWorld]: Tried to add entity minecraft:spider but it was marked as removed already
106 | 05.10 19:18:00 [Server] Server thread/WARN [minecraft/ServerWorld]: Tried to add entity minecraft:spider but it was marked as removed already
107 | 05.10 19:19:08 [Disconnect] User RayWoss has disconnected, reason: Disconnected
108 | 05.10 19:19:08 [Server] Server thread/INFO [minecraft/DedicatedServer]: RayWoss left the game
109 |

**Comment by TheCyberBrick** [comment]
This is because vanilla spider entities are being replaced upon spawning (hence the warning that it was removed). Will investigate why this is happening though and whether it can be avoided.

**Comment by BugmanBugman** [comment]
Do you think it’s possible to add the modded behavior to the vanilla spiders instead of replacing them outright? Feels like this route could break mod compat that depends on the vanilla spider

**Comment by TheCyberBrick** [comment]
I might do that at some point. However, the custom spiders replace significant portions of the mob's logic and rendering, so I'm not sure whether this would really improve compatibility. It'd certainly be more prone to breaking :P
