### ISSUE TITLE
[1.15.2] Crash after attacking a spider

### ISSUE THREAD

**Issue by anIceyGirl** [TheCyberBrick/Spiders-2.0#19]
After attacking a spider, the game crashes. I'll be honest, there's not that much to what caused this crash, but the internal details are somewhat beyond me.

[crash-2020-10-08_06.24.53-server.txt](https://github.com/TheCyberBrick/Spiders-2.0/files/5347151/crash-2020-10-08_06.24.53-server.txt)

**Comment by TheCyberBrick** [comment]
Could you please try without the Performant mod? I suspect it's caused by that.
