### ISSUE TITLE
Non-climbable Blocks

### ISSUE THREAD

**Issue by TheCyberBrick** [TheCyberBrick/Spiders-2.0#20]
KingCloudian: 
Such a great mod and adds a refreshing dynamic, but it is nearly impossible to make a farm out of spiders. They always stick to the a ledge if they are pushed off, perhaps making glazed terracotta a non-stickable block for spiders? This would stay true to how slimeblocks do not stick to them (glazed Terracotta) as well

**Comment by SandwichHorror** [comment]
I wonder if a config-defined blacklist would be possible for this feature, so certain modded blocks can be made non-climbable, or the entire feature could be disabled by leaving no valid blocks.

**Comment by TheCyberBrick** [comment]
Yes, it uses [Tags](https://minecraft.gamepedia.com/Tag). Not sure whether I'll add a config to 1.12.
