### ISSUE TITLE
Can uninstall without crashing

### ISSUE THREAD

**Issue by ak1dd** [TheCyberBrick/Spiders-2.0#23]
First, thanks for this... I really like what you've done and wish all the mobs could have such treatment.

I have the spider spawner issue that others have described.  This is in my survival world that has taken many months to build.

Since spiders-2.0-1.16.3-1.0.2 is the only thing I've added recently,  I quit the game, removed spiders2.0 jar from the mod fold and restarted.   MC crashes before the world appears.   Tried again.  Crash.    So I put the spiders 2.0 jar back in the mod folder and the game loads.    I have no other mods that alter mobs or spawners in any way

 Is there any way I can disable or remove this mod or can I not play my world again without it?

![mWlaw8f](https://user-images.githubusercontent.com/38289720/96360535-fbb72000-1115-11eb-9eca-40b3788d54c1.jpg)

Again, thanks for your work.

**Comment by TheCyberBrick** [comment]
Please attach the whole crash report. Though, from what I can tell from this small excerpt, this can't be caused by my mod (I also can't reproduce it myself).

**Comment by ak1dd** [comment]
I am running the latest forge Build: 1.16.3-34.1.23 - Fri Oct 16 19:10:02 GMT 2020. For whatever reason,  I individually disabled each of the 11 mods I have and reenabled them back if MC would still load.  The only single mod I couldn't load without was spiders 2.0.   As a last attempt I removed EVERY mod, ran MC and it loaded.  I exited and saved and put back every mod except Spiders2.0 and now MC and each of the mods (tested each) load and work as before.

Perhaps it is a forge conflict?  That seems unlikely because I tested having only Spiders and Forge and it does work now.  I understand you can't chase everything down and likely this isn't an issue with your code but somehow my issue was related to Spider 2.0.   Here is my modlist in case it is meaningful.  I won't close this in case it is helpful to you otherwise I guess it is "closed".

All of them updated to the latest 1.16.3 releases (except Forge which isn't released as final and Optifine which is still a "preview")

- Appleskin -forge
- Backpacked, Bookshelf
- Enchantment Descriptions
- Gravestone, HWLA-forge
- Inventory profiles-forge
- potiondescription
- Optifine_1.163 - G4
- Xaeros Minimap
- Xaeros WorldMap.   

I eagerly await your fixes for the spawning bug.   Love your work.
[crash-2020-10-19_09.04.12-client.txt](https://github.com/TheCyberBrick/Spiders-2.0/files/5400108/crash-2020-10-19_09.04.12-client.txt)

**Comment by TheCyberBrick** [comment]
I still fail to reproduce this even with the exactly same Forge version, however since this crash is occurring in a recently changed piece of code from Forge you should be able to downgrade Forge to recommended (34.1.0) and then load the world with that (after making a backup). Or at least try reinstalling Forge, it seems like somehow your installation is corrupt.
In any case, this is not caused by Spiders 2.0 and there's nothing I can do to fix it. If it keeps happening even after reinstalling etc. I recommend you report it to Forge (but only if you've tested this with no other mod installed except Spiders 2.0 and made sure that it's not caused by any other mods).

**Comment by TheCyberBrick** [comment]
The issue of spawners spawning infinite spiders is now resolved for 1.15.2+
I'll need to find another workaround for 1.12.2 though.
