### ISSUE TITLE
[1.16.3] Spiders always facing one direction.

### ISSUE THREAD

**Issue by pajakkox** [TheCyberBrick/Spiders-2.0#27]
Version: Spiders 2.0 1.16.3 v1.0.4 
In this picture, they are chasing me.
![2020-11-06_15 32 56](https://user-images.githubusercontent.com/62602125/98377793-8a4bfc80-2045-11eb-9a5d-05627766fc29.png)

**Comment by TheCyberBrick** [comment]
I can't reproduce this with Forge and Spiders 2.0 only. Does this happen reliably for you?
It seems you also have other mods installed, please try it without those mods and/or try to pin down which combination makes it happen.

**Comment by pajakkox** [comment]
Sorry, i totally forgot bout this, i'm gonna do this rn.

**Comment by pajakkox** [comment]
I'm gonna be totally honest with you, i changed nothing, just created new world and it looks like everything is okay.
I think this was a one time bug (?) or something like that.

**Comment by TheCyberBrick** [comment]
Fair enough, thanks for letting me know! If it pops up again feel free to create a new issue.
