### ISSUE TITLE
[Request] will the mod be backported to 1.15.2?

### ISSUE THREAD

**Issue by ghost** [TheCyberBrick/Spiders-2.0#3]
This would seriously improve the gaming experience :)

**Comment by TheCyberBrick** [comment]
Perhaps once I feel like the mod is "finished". I can't and won't maintain 10 different versions at once. But once the mod is in a reasonably finished state I might make some ports and just continue maintaining the more up-to-date versions.

**Comment by ghost** [comment]
yes. good to hear of the possibility.. I'll patiently wait then :)
