### ISSUE TITLE
Skeletons spawning randomly

### ISSUE THREAD

**Issue by ekiplier** [TheCyberBrick/Spiders-2.0#30]
I've been experiencing a bug where skeletons spawn in throughout the world without any possible interaction. They don't get affected by anything (even gravity) except tnt explosions and a first hit you can land on them before they turn into utter ghosts, or just rendered entities with no AI. Someone has already pointed out this bug so I'm gonna post my modpack here as well to make it easier to find the mod that's in conflict with Spiders 2.0.

![Captura de ecrã 2020-11-08 004505](https://user-images.githubusercontent.com/74121461/98454370-af329380-215b-11eb-9159-8dd55360c45a.png)

**Comment by TheCyberBrick** [comment]
Duplicate #26
