### ISSUE TITLE
Cave Spider Spawner bug 1.16.3 mod version 1.0.2

### ISSUE THREAD

**Issue by Kratos-Lee520** [TheCyberBrick/Spiders-2.0#31]
The cave spider spawner is spawning them constantly without stopping causing hundreds to be there and lag the game. I removed the mod and it fixed it entirely, so it is this mod. I changed to the 1.0.4 version and it fixed it so maybe the 1.0.2 version needs to be removed if there is this big of an issue with it.

**Comment by TheCyberBrick** [comment]
Yep, that was fixed in the following version. I won't remove the old versions though because that could break modpacks.
