### ISSUE TITLE
[1.15.2] Compatability issue between performant and spiders 2.0.

### ISSUE THREAD

**Issue by ghost** [TheCyberBrick/Spiders-2.0#33]
Hi,
I'm running into an issue where if I run performant with spiders 2.0, the spiders won't be able to climb up surfaces even if they're 1 block tall.

**Comment by TheCyberBrick** [comment]
Hey! Performant is closed source, so I can't look at its source code properly to figure out why it's not working, all I know is that Performant changes how path finding works and thus breaks Spiders 2.0. Unfortunately, the author of Performant has said that adding compatibility would likely not be possible, so I don't think this will get resolved.
