### ISSUE TITLE
Animations not working with Optifine 1.16.4 HD U G6

### ISSUE THREAD

**Issue by Baldur9** [TheCyberBrick/Spiders-2.0#38]
Animations not working with Optifine HD U G6/preview G7_pre1. They were working on previous versions of Optifine. I am using Minecraft 1.16.4, Forge 35.1.37. Custom mob models are from Overgrowth resource pack. The spiders will still walk on ceilings/walls, but do so right-side up. Expected behavior is that they are clinging to the walls.

If this can only be fixed by Optifine, I will try to open a bug there instead.

![2021-01-16_21 15 07](https://user-images.githubusercontent.com/77427648/104832874-73960300-5849-11eb-94e1-a5bb0210ddb6.png)

**Comment by PenumbraStar** [comment]
Same Issue but on Optifine HD U G6_pre1, i can provide logs if required, hopefully we can resolve this without optifine interference.

**Comment by TheCyberBrick** [comment]
Yes, please also report this to Optifine. I'll do some testing myself later.

**Comment by lucassimon963** [comment]
If you use the optifine version: preview OptiFine 1.16.5 HD U G7 pre4 then the animations work fine.
The optifine version looks stable as far as I have noticed.

**Comment by Baldur9** [comment]
Confirmed this is working on 1.16.5 / Optifine HD U G7 pre4. @TheCyberBrick : I think this can be closed now

**Comment by PenumbraStar** [comment]
Can also confirm on Optifine HD U G8 Pre1

**Comment by ghost** [comment]
Yes, I can confirm that the animations are working correctly on Optifine HD U G8. This issue can be closed

**Comment by Baldur9** [comment]
Closing issue, this is resolved. This is confirmed working now by myself and other users and to have been an Optifine issue.
