### ISSUE TITLE
[Crash Report] Whenever A Spider Is Spawned I Crash.

### ISSUE THREAD

**Issue by UberbeastX** [TheCyberBrick/Spiders-2.0#43]
[Spiders 2.0 Crash Report.txt](https://github.com/TheCyberBrick/Spiders-2.0/files/6641585/Spiders.2.0.Crash.Report.txt)

This is the crash I got whenever spiders showed up I have no idea why I crash, hopefully it's fixable.

**Comment by TheCyberBrick** [comment]
This crash seems to be caused by ActualMusic.
