### ISSUE TITLE
Not Compatible with Mo' Bends

### ISSUE THREAD

**Issue by BlindWorship** [TheCyberBrick/Spiders-2.0#48]
[crash-2021-08-10_04.51.57-client.txt](https://github.com/TheCyberBrick/Spiders-2.0/files/6960446/crash-2021-08-10_04.51.57-client.txt)

**Comment by TheCyberBrick** [comment]
Your version of Mo' Bends is incompatible. You'll have to replace it with the latest 1.12 release: https://www.curseforge.com/minecraft/mc-mods/mo-bends/files/2984182
