### ISSUE TITLE
Compatibility with "extract poison"

### ISSUE THREAD

**Issue by Blugori** [TheCyberBrick/Spiders-2.0#5]
Minecraft version : 1.16.3

Hi, I enjoy a lot playing with your mod, and I was wondering if you could add compatibility for the mod "extract poison". This mod allows the player to use an empty bottle on a cave spider to get a bottle of poison, but since your mod replace the vanilla spiders, "extract poison" isnt working.

Thanks for your work !

**Comment by Blugori** [comment]
The creator of extract poison fixed it !

**Comment by TheCyberBrick** [comment]
Ah, nice! :)
