### ISSUE TITLE
Server crash (Minecraft v. 1.12.2)

### ISSUE THREAD

**Issue by SeagalKru** [TheCyberBrick/Spiders-2.0#59]
(Google translation from Russian)
Server crash after installing your mod.
Thank you for attention!

[crash-2022-12-15_17.52.14-server.txt](https://github.com/TheCyberBrick/Spiders-2.0/files/10238063/crash-2022-12-15_17.52.14-server.txt)

**Comment by SeagalKru** [comment]
Is the developer of this mod still working on the mod, or has it been abandoned and the mod is no longer supported?

**Comment by MagmaSlime123** [comment]
Dead mod, no.

**Comment by SeagalKru** [comment]
Got it, thank you.
I'll close it then.
