### ISSUE TITLE
[1.12.2][Bug] Spiders refuse to enter water; become braindead if forced to swim

### ISSUE THREAD

**Issue by SandwichHorror** [TheCyberBrick/Spiders-2.0#7]
Spiders will not enter water, preferring to exit onto land immediately, but they will straddle the edge of the water, making them easy pickings for simply punching out of range.

If forced into water beyond the shoreline, they will simply bob up and down for eternity, only turning around to look at the closest entity but never actively pursuing or wandering.

![2020-10-02_20 32 29](https://user-images.githubusercontent.com/59847281/94979687-36a03d80-04f2-11eb-848a-8001d46ea1f8.png)

**Comment by TheCyberBrick** [comment]
Should now be fixed.
