### ISSUE TITLE
[1.12][Bug]Pathfinding/Collision Issues and Spinning with Mo'Bends

### ISSUE THREAD

**Issue by SandwichHorror** [TheCyberBrick/Spiders-2.0#9]
When Mo'Bends is installed and the spiders are on a wall or ceiling, the spiders have a very high chance to randomly begin spinning at high speed, apparently unable to pathfind anywhere. Additionally, they seem to get stuck even on simple ascents or descents very frequently, often causing them to lose their target (and then begin spinning again, and not in the spinning-a-web sense, but in the 1984 Dead or Alive sense)

**Comment by TheCyberBrick** [comment]
Should now be fixed.
